version: "3"
services:
  rails:
    build:
      context: .
    volumes:
      - .:/myapp
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3000:3000"
    tty:
      true
    stdin_open: true
