version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.6
  ruby: circleci/ruby@2.1.1
  node: circleci/node@5.2.0
  git-shallow-clone: guitarrapc/git-shallow-clone@2.8.0

commands:
  yarn-install:
    steps:
      - node/install:
          install-yarn: true
          node-version: 18.18.2
          yarn-version: 1.22.15
      - node/install-packages:
          pkg-manager: yarn
          include-branch-in-cache-key: false
          cache-version: v7

  install-browser-tools:
    steps:
      # TODO: chromedriverのinstallに失敗していたためバージョンを指定しているが解消されたらバージョン指定を削除する
      #       ref: https://github.com/CircleCI-Public/browser-tools-orb/issues/108
      - browser-tools/install-chrome:
          chrome-version: 116.0.5845.96
          replace-existing: true
      - browser-tools/install-chromedriver
      - run:
          name: Install Playwright Dependencies
          command: |
            yarn run playwright install-deps chrome
            yarn run playwright install ffmpeg
  
  bundle-install:
    steps:
      - ruby/install-deps:
          key: gems-v1
          with-cache: true
          clean-bundle: true
          include-branch-in-cache-key: false

jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - run:
          name: apt install
          command: |
            sudo apt update
            sudo apt install libmcrypt-dev libmysqlclient-dev libjemalloc-dev libjemalloc2 gnupg
      - git-shallow-clone/checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "Gemfile.lock" }}
      - bundle-install
      - yarn-install
      - install-browser-tools
      - run:
          name: run rspec
          command: bundle exec rspec

workflows:
  build_and_analyze:
    jobs:
      - rspec:
          filters:
            branches:
              only:
                - main