version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.6
  ruby: circleci/ruby@2.1.1
  node: circleci/node@5.2.0

primary: &primary
  image: cimg/ruby:3.1.4-browsers
  environment:
    ARTIFACTS_DIR: /tmp/artifacts
    TESTRESULTS_DIR: /tmp/results

executors:
  default:
    docker:
      - <<: *primary

commands:
  yarn-install:
    steps:
      - node/install:
          install-yarn: true
          node-version: 18.18.2
          yarn-version: 1.22.15
      - node/install-packages:
          pkg-manager: yarn
          include-branch-in-cache-key: false
          cache-version: v7

  install-browser-tools:
    steps:
      # TODO: chromedriverのinstallに失敗していたためバージョンを指定しているが解消されたらバージョン指定を削除する
      #       ref: https://github.com/CircleCI-Public/browser-tools-orb/issues/108
      - browser-tools/install-chrome:
          chrome-version: 116.0.5845.96
          replace-existing: true
      - browser-tools/install-chromedriver
      - run:
          name: Install Playwright Dependencies
          command: |
            yarn run playwright install-deps chrome
            yarn run playwright install ffmpeg
  
  bundle-install:
    steps:
      - ruby/install-deps:
          key: gems-v1
          with-cache: true
          clean-bundle: true
          include-branch-in-cache-key: false

jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.2.2
    environment:
      TESTRESULTS_DIR: /tmp/results
    steps:
      - run:
          name: apt install
          command: |
            sudo apt update
            sudo apt install libmcrypt-dev libmysqlclient-dev libjemalloc-dev libjemalloc2 gnupg
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "Gemfile.lock" }}
      - bundle-install
      - install-browser-tools
      - run:
          name: run rspec
          command: |
            TEST_FILES=$(circleci tests glob "spec/**/*_spec.rb")
            echo "$TEST_FILES" | circleci tests run --command="xargs bundle exec rspec \
              --failure-exit-code=0  \
              --error-exit-code=1 \
              -r rspec_junit_formatter \
              -f RspecJunitFormatter \
              -o ${TESTRESULTS_DIR}/rspec.xml \
              -f progress" \
              --split-by=timings
            # NOTE: circleci tests runコマンドを利用すると、実行結果が出力されるようになっため、
            #       `/tmp/rspec-examples.txt`に出力されたファイル名を抽出する。
            if [ -e ./tmp/rspec-examples.txt]
            then
              grep -o '[^ ]*_spec.rb[^ ]*' ./tmp/rspec-examples.txt | cut -d'[' -f1 | awk '!a[$0]++{print}' > /tmp/rspec_files_list.txt
            fi
      - store_test_results:
          path: /tmp/results
      - store_artifacts:
          path: /tmp/rspec_files_list.txt
  
  assets:
    executor: default
    steps:
      - checkout
      - yarn-install
      - persist_to_workspace:
          root: .
          paths:
            - "./node_modules"

workflows:
  build_and_analyze:
    jobs:
      - assets
      - rspec:
          requires:
            - assets
          filters:
            branches:
              only:
                - main